version: '3.8'

services:
  web:
    build: .
    container_name: mlops_fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password  # <-- هنا كلمة السر التي يرسلها التطبيق
      - DB_NAME=olist
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: mlops_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  # <-- هنا كلمة السر التي تُنشأ بها قاعدة البيانات
      POSTGRES_DB: olist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: